Let autoreconf sort out libtool and anything else required.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,18 +1,25 @@
 #! /bin/sh
 set -x
 
+command -v libtool >/dev/null 2>&1
+if  [ $? -ne 0 ]; then
+    echo "autogen.sh: error: could not find libtool.  libtool is required to run autogen.sh." 1>&2
+    exit 1
+fi
+
+command -v autoreconf >/dev/null 2>&1
+if [ $? -ne 0 ]; then
+    echo "autogen.sh: error: could not find autoreconf.  autoconf and automake are required to run autogen.sh." 1>&2
+    exit 1
+fi
+
 rm -rf admin
 mkdir admin
 
-if [ -e /usr/bin/glibtoolize ] ; then
-    glibtoolize --force
-elif [ -e /usr/bin/libtoolize ] ; then
-    libtoolize --force
-elif [ -e /usr/local/bin/libtoolize ] ; then
-    libtoolize --force
-else
-   echo "ERROR: I cannot find libtoolize or glibtoolize!"
-   exit 1
+autoreconf --install --force --verbose -I admin
+if [ $? -ne 0 ]; then
+    echo "autogen.sh: error: autoreconf exited with status $?" 1>&2
+    exit 1
 fi
 
 if [ -e /usr/local/share/aclocal ] ; then
@@ -20,6 +27,8 @@ if [ -e /usr/local/share/aclocal ] ; then
 else
    aclocal -I /usr/share/aclocal
 fi
+
 autoheader
 automake --gnu --add-missing --copy
 autoconf
+
